# Generated by Django 4.2.7 on 2023-11-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_table_alter_person_table'),
        ('Project', '0003_alter_employee_project_table_alter_project_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_project',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='employee_project',
            name='pid',
        ),
        migrations.AddField(
            model_name='employee_project',
            name='e_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='eid', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='employee_project',
            name='p_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='Project.project'),
        ),
    ]
