# Generated by Django 4.2.7 on 2023-11-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_tools', '0002_alter_codingtools_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='codingtools',
            table='codingtools',
        ),
        migrations.AlterModelTable(
            name='employee_codingtools',
            table='employee_codingtools',
        ),
    ]
